// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4TSvvfp0fXLsXBacjPQYUFnPc3Q1o00',
    appId: '1:624841070602:web:5c5bf281dae3c2898667f3',
    messagingSenderId: '624841070602',
    projectId: 'flutter-application-1-ee2f2',
    authDomain: 'flutter-application-1-ee2f2.firebaseapp.com',
    storageBucket: 'flutter-application-1-ee2f2.appspot.com',
    measurementId: 'G-3PSWGF5PCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEoxMdGOnezKj_5AD-AgPt4tsLIyY7Wh0',
    appId: '1:624841070602:android:009ceb35a81819f18667f3',
    messagingSenderId: '624841070602',
    projectId: 'flutter-application-1-ee2f2',
    storageBucket: 'flutter-application-1-ee2f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVQpFkj0KZLL3UhXkcO06X0kuegfvj8Hs',
    appId: '1:624841070602:ios:88022e13b75c59d58667f3',
    messagingSenderId: '624841070602',
    projectId: 'flutter-application-1-ee2f2',
    storageBucket: 'flutter-application-1-ee2f2.appspot.com',
    iosClientId: '624841070602-aje4rms688uocsu6j4s6l072hpcbu5m7.apps.googleusercontent.com',
    iosBundleId: 'com',
  );
}
